# Generated by Django 5.0.7 on 2024-12-09 19:48

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoice", "0001_initial"),
        ("order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="invoiceevent",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="invoice.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoiceevent",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_events",
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="invoiceevent",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="invoice_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="invoice_meta_idx"
            ),
        ),
    ]
