# Generated by Django 5.0.7 on 2025-01-22 15:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxi", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Truck", "Truck"),
                            ("Lorry", "Lorry"),
                            ("Bus", "Bus"),
                            ("Van", "Van"),
                            ("Car", "Car"),
                            ("Bike", "Bike"),
                        ],
                        default="Bike",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("standing_by", "Standing by"),
                            ("pending", "Pending"),
                            ("shipping", "Shipping"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "route",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("last_pos_update", models.DateTimeField(auto_now=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_courier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taxi.vehicle"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_name", models.CharField(max_length=255)),
                (
                    "receiver_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        region=None,
                    ),
                ),
                (
                    "receiver_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("pickup_location", models.CharField(max_length=255)),
                ("delivery_location", models.CharField(max_length=255)),
                ("pickup_time", models.TimeField()),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mm", "mm"),
                            ("cm", "cm"),
                            ("dm", "dm"),
                            ("m", "m"),
                            ("km", "km"),
                            ("ft", "ft"),
                            ("yd", "yd"),
                            ("inch", "inch"),
                            ("sq_mm", "sq_mm"),
                            ("sq_cm", "sq_cm"),
                            ("sq_dm", "sq_dm"),
                            ("sq_m", "sq_m"),
                            ("sq_km", "sq_km"),
                            ("sq_ft", "sq_ft"),
                            ("sq_yd", "sq_yd"),
                            ("sq_inch", "sq_inch"),
                            ("cubic_millimeter", "cubic_millimeter"),
                            ("cubic_centimeter", "cubic_centimeter"),
                            ("cubic_decimeter", "cubic_decimeter"),
                            ("cubic_meter", "cubic_meter"),
                            ("liter", "liter"),
                            ("cubic_foot", "cubic_foot"),
                            ("cubic_inch", "cubic_inch"),
                            ("cubic_yard", "cubic_yard"),
                            ("qt", "qt"),
                            ("pint", "pint"),
                            ("fl_oz", "fl_oz"),
                            ("acre_in", "acre_in"),
                            ("acre_ft", "acre_ft"),
                            ("g", "g"),
                            ("lb", "lb"),
                            ("oz", "oz"),
                            ("kg", "kg"),
                            ("tonne", "tonne"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mm", "mm"),
                            ("cm", "cm"),
                            ("dm", "dm"),
                            ("m", "m"),
                            ("km", "km"),
                            ("ft", "ft"),
                            ("yd", "yd"),
                            ("inch", "inch"),
                            ("sq_mm", "sq_mm"),
                            ("sq_cm", "sq_cm"),
                            ("sq_dm", "sq_dm"),
                            ("sq_m", "sq_m"),
                            ("sq_km", "sq_km"),
                            ("sq_ft", "sq_ft"),
                            ("sq_yd", "sq_yd"),
                            ("sq_inch", "sq_inch"),
                            ("cubic_millimeter", "cubic_millimeter"),
                            ("cubic_centimeter", "cubic_centimeter"),
                            ("cubic_decimeter", "cubic_decimeter"),
                            ("cubic_meter", "cubic_meter"),
                            ("liter", "liter"),
                            ("cubic_foot", "cubic_foot"),
                            ("cubic_inch", "cubic_inch"),
                            ("cubic_yard", "cubic_yard"),
                            ("qt", "qt"),
                            ("pint", "pint"),
                            ("fl_oz", "fl_oz"),
                            ("acre_in", "acre_in"),
                            ("acre_ft", "acre_ft"),
                            ("g", "g"),
                            ("lb", "lb"),
                            ("oz", "oz"),
                            ("kg", "kg"),
                            ("tonne", "tonne"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("fragility", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("created", "Created"),
                            ("pickup_scheduled", "Pickup scheduled"),
                            ("picked_up", "Picked up"),
                            ("in_transit", "In transit"),
                            ("out_for_delivery", "Out for delivery"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[("cash", "Cash"), ("card", "Card")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "sender_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "rider_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("receipts", models.FileField(blank=True, null=True, upload_to="")),
                ("package_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cancelled_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ref_code", models.CharField(editable=False, max_length=8)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.logisticstype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "PENDING"),
                            (2, "REJECTED"),
                            (3, "SHIPPING"),
                            (4, "SHIPPED"),
                            (5, "FAILED"),
                            (6, "TIMED_OUT"),
                        ],
                        default=1,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.courier",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.package",
                    ),
                ),
            ],
        ),
    ]
