# Generated by Django 5.0.7 on 2024-12-09 19:48

import django.db.models.deletion
from django.db import migrations, models

import core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=core.utils.json_serializer.CustomJsonEncoder,
                        null=True,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channel.channel",
                    ),
                ),
            ],
            options={
                "permissions": (("manage_plugins", "Manage plugins"),),
                "unique_together": {("identifier", "channel")},
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.TextField()),
                (
                    "plugin_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="plugins.pluginconfiguration",
                    ),
                ),
            ],
        ),
    ]
