# Generated by Django 5.0.7 on 2024-11-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_prices_vatlayer", "0003_auto_20180316_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratetypes",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="vat",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
