# Generated by Django 5.0.7 on 2024-12-15 13:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import realestate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("apartment", "Apartment"),
                            ("office", "Office"),
                            ("warehouse", "Warehouse"),
                            ("land", "Land"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_agent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_area",
                    models.CharField(
                        choices=[
                            ("R", "Residential"),
                            ("C", "Commercial"),
                            ("A", "Agricultural"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True)),
                ("bedrooms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "property_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("ceiling_height", models.FloatField(blank=True, null=True)),
                ("bathrooms", models.PositiveIntegerField(blank=True, null=True)),
                ("garage", models.IntegerField(default=0)),
                ("square_feet", models.FloatField()),
                ("lot_size", models.FloatField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="image")),
                (
                    "property_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                            ("pending_review", "Pending Review"),
                            ("rejected", "Rejected"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=40,
                    ),
                ),
                (
                    "property_for",
                    models.CharField(
                        choices=[
                            ("B", "Buy"),
                            ("S", "Sale"),
                            ("R", "Rent"),
                            ("L", "Lease"),
                        ],
                        default="S",
                        max_length=5,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("year_built", models.PositiveIntegerField(default=0)),
                (
                    "free_from",
                    models.DateField(blank=True, default=django.utils.timezone.now),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.address",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings_agent",
                        to="realestate.agent",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.listingtype",
                        verbose_name="Listing type",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "permissions": [
                    ("can_create_update_listing", "Can create and update listing"),
                    ("can_publish_listing", "Can publish listing"),
                    ("can_submit_listing_for_review", "Can submit listing for review"),
                    ("can_reject_listing", "Can reject listing"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ListingFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="listings/files/"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("for_customer", models.BooleanField(default=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="realestate.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=realestate.models.listing_dir_path),
                ),
                ("short_description", models.TextField(blank=True, max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="realestate.listing",
                    ),
                ),
            ],
        ),
    ]
